require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.nvim-tree"
require "user.treesitter"
require "user.toggleterm"
require "user.lsp"
require "user.autopairs"
require "user.gitsigns"
require "user.statusline"
-- require "user.bufferline"
require "user.indent_guide"
require "user.telescope"
require "user.finecmd"
require "user.formatter"
